trigger:
- main

pool: Default

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
    - job: BuildJob
      steps:
        - task: PowerShell@2
          displayName: 'Set sys_id variable'
          inputs:
            targetType: 'inline'
            script: |
              # Set the variable sys_id
              $sys_id = "12345"
              Write-Host "##vso[task.setvariable variable=sys_id;isOutput=true]$sys_id"
              Write-Host "sys_id has been set to $sys_id"

- stage: Deploy
  displayName: 'Deploy Stage'
  dependsOn: Build  # This ensures Deploy runs after Build
  jobs:
    - job: DeployJob
      steps:
        - task: PowerShell@2
          displayName: 'Access sys_id from Build stage'
          inputs:
            targetType: 'inline'
            script: |
              # Access the output variable from the Build stage
              $sys_id_from_build = $(Build.BuildJob.sys_id)
              Write-Host "The sys_id passed from Build stage is: $sys_id_from_build"
