trigger:
- main

pool: Default

variables:
  sys_id: ''

stages:
  - stage: assignVariable
    jobs:
      - job:
        steps:
          # Task 1: Assign value to sys_id variable
          - task: PowerShell@2
            displayName: 'Assign value to sys_id'
            inputs:
              targetType: 'inline'
              script: |
                $sys_id = "12345"  # You can change this value as needed
                Write-Host "##vso[task.setvariable variable=sys_id;isOutput=true]$sys_id"
                Write-Host "sys_id has been set to $sys_id"

  - stage: printVariable
    dependsOn: assignVariable
    jobs:
      - job:
        steps:
          # Task 2: Output the value of sys_id
          - task: PowerShell@2
            displayName: 'Write sys_id value'
            inputs:
              targetType: 'inline'
              script: |
                $sys_id_from_build = $(Build.sys_id)
                Write-Host "The value of sys_id is: $sys_id_from_build"
