resources:
 repositories:
   - repository: Mock_code_repo
     type: github
     endpoint: GitHubConn
     name: vinitamishra15/Mock_code_repo
   - repository: BranchMerge
     type: github
     endpoint: GitHubConn
     name: vinitamishra15/BranchMerge

trigger:
- main

pool: Default

variables:
  serviceNowInstance: 'https://dev212832.service-now.com'
  userName: 'admin'
  password: 'tt!rSy25Y^SK'
  changeRequestSysId: ''

stages:
  - stage: CreateChangeRequest
    jobs:
      - job: CreateChange
        steps:
          - task: PowerShell@2
            name: CreateChangeTask
            inputs:
              targetType: 'inline'
              script: |
                $url = "$(serviceNowInstance)/api/now/table/change_request"
                $changeRequestSysId = '1234'
                Write-Output "##vso[task.setvariable variable=changeRequestSysId;isOutput=true]$changeRequestSysId"
                Write-Host "Change request created with $changeRequestSysId"

          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "Debug: changeRequestSysId is set to $(changeRequestSysId)"

  - stage: ApprovalCheck
    dependsOn: CreateChangeRequest
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main')) # Run only on production branch if needed
    jobs:
      - job: WaitForApproval
        variables:
          changeRequestSysId: $[ dependencies.CreateChangeRequest.outputs['CreateChange.CreateChangeTask.changeRequestSysId'] ]
        steps:
          - task: PowerShell@2
            inputs:
              targetType: 'inline'
              script: |
                Write-Host "sys_id: $(changeRequestSysId)"
                Write-Host "sys_id 2 : $changeRequestSysId"
                Write-Host "sys_id 2 : $env:changeRequestSysId"
                Write-Host "Value: $[ dependencies.CreateChangeRequest.outputs['CreateChange.CreateChangeTask.changeRequestSysId'] ]"